/**
 * Comment by ghost ide
 *
 * @author: Ninjacoder
 */
package ir.hanzodev1375.ghostide.codeeditors.langs.solidity;

import ir.hanzodev1375.ghostide.codeeditors.langs.simple.SimpleLangConfig;
import ir.hanzodev1375.ghostide.codeeditors.langs.simple.SimpleLanguage;

public class SolidityLanguage extends SimpleLanguage {

  private static final String[] WORDS = {
    "pragma",
    "solidity",
    "import",
    "contract",
    "abstract",
    "interface",
    "library",
    "is",
    "using",
    "struct",
    "enum",
    "function",
    "modifier",
    "event",
    "error",
    "emit",
    "constructor",
    "fallback",
    "receive",
    "mapping",
    "address",
    "payable",
    "memory",
    "calldata",
    "storage",
    "external",
    "public",
    "internal",
    "private",
    "pure",
    "view",
    "returns",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "break",
    "continue",
    "require",
    "assert",
    "revert",
    "new",
    "delete",
    "this",
    "super",
    "virtual",
    "override",
    "constant",
    "immutable",
    "indexed",
    "anonymous",
    "unchecked",
    "assembly",
    "try",
    "catch",
    "type",
    "bool",
    "string",
    "bytes",
    "bytes1",
    "bytes2",
    "bytes3",
    "bytes4",
    "bytes5",
    "bytes6",
    "bytes7",
    "bytes8",
    "bytes9",
    "bytes10",
    "bytes11",
    "bytes12",
    "bytes13",
    "bytes14",
    "bytes15",
    "bytes16",
    "bytes17",
    "bytes18",
    "bytes19",
    "bytes20",
    "bytes21",
    "bytes22",
    "bytes23",
    "bytes24",
    "bytes25",
    "bytes26",
    "bytes27",
    "bytes28",
    "bytes29",
    "bytes30",
    "bytes31",
    "bytes32",
    "int",
    "int8",
    "int16",
    "int24",
    "int32",
    "int40",
    "int48",
    "int56",
    "int64",
    "int72",
    "int80",
    "int88",
    "int96",
    "int104",
    "int112",
    "int120",
    "int128",
    "int136",
    "int144",
    "int152",
    "int160",
    "int168",
    "int176",
    "int184",
    "int192",
    "int200",
    "int208",
    "int216",
    "int224",
    "int232",
    "int240",
    "int248",
    "int256",
    "uint",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "uint128",
    "uint256",
    "wei",
    "gwei",
    "szabo",
    "finney",
    "ether",
    "seconds",
    "minutes",
    "hours",
    "days",
    "weeks",
    "years",
    "keccak256",
    "sha256",
    "sha3",
    "ripemd160",
    "ecrecover",
    "addmod",
    "mulmod",
    "selfdestruct",
    "blockhash",
    "gasleft",
    "balance",
    "transfer",
    "send",
    "call",
    "delegatecall",
    "staticcall",
    "length",
    "push",
    "pop",
    "wrap",
    "unwrap"
  };

  private static final SnippetDef[] SNIPPETS = {
    new SnippetDef(
        "contract",
        "Snippet - Contract",
        "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.0;\n\ncontract ${1:Name} {\n    $0\n}"),
    new SnippetDef(
        "sp",
        "Snippet - Function",
        "function ${1:name}(${2:args}) ${3:public} ${4:view} returns (${5:type}) {\n    $0\n}"),
    new SnippetDef("event", "Snippet - Event", "event ${1:Name}(${2:type indexed name});"),
    new SnippetDef(
        "mapping", "Snippet - Mapping", "mapping(${1:address} => ${2:uint256}) public ${3:name};"),
    new SnippetDef(
        "modifier",
        "Snippet - Modifier",
        "modifier ${1:name}() {\n    require(${2:condition}, \"${3:message}\");\n    _;\n}"),
  };

  public SolidityLanguage() {
    super(solidityConfig(), WORDS, SNIPPETS);
  }

  private static SimpleLangConfig solidityConfig() {
    var cfg = new SimpleLangConfig();
    cfg.lineComments = new String[] {"//"};
    cfg.blockComment = true;
    return cfg;
  }
}
