package ir.hanzodev1375.ghostide.refactor.rename.model;

public enum SourceEditType {
  PACKAGE_DECLARATION,
  IMPORT_STATEMENT,
  STATIC_IMPORT_STATEMENT,
  FULLY_QUALIFIED_REFERENCE,
  MANIFEST_PACKAGE_ATTRIBUTE,
  MANIFEST_PROVIDER_AUTHORITY,
  GRADLE_NAMESPACE,
  GRADLE_APPLICATION_ID,
  BUILD_CONFIG_REFERENCE,
  REFLECTION_STRING_REFERENCE,
  DIRECTORY_MOVE,
  EMPTY_DIRECTORY_DELETION
}
