package ir.hanzodev1375.ghostide.materialfileicon.core.langcolor;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class LanguageColors {
  public static final Map<String, String> GITHUB_LANGUAGE_COLORS;
  public static final Map<String, String> EXTENSION_COLORS;

  static {
    Map<String, String> map = new HashMap<>();
    map.put("1C Enterprise", "#814CCC");
    map.put("2-Dimensional Array", "#38761D");
    map.put("4D", "#004289");
    map.put("ABAP", "#E8274B");
    map.put("ABAP CDS", "#555E25");
    map.put("AGS Script", "#B9D9FF");
    map.put("AIDL", "#34EB6B");
    map.put("AL", "#3AA2B5");
    map.put("ALGOL", "#D1E0DB");
    map.put("AMPL", "#E6EFBB");
    map.put("ANTLR", "#9DC3FF");
    map.put("API Blueprint", "#2ACCA8");
    map.put("APL", "#5A8164");
    map.put("ASP.NET", "#9400FF");
    map.put("ATS", "#1AC620");
    map.put("ActionScript", "#882B0F");
    map.put("Ada", "#02F88C");
    map.put("Adblock Filter List", "#800000");
    map.put("Adobe Font Metrics", "#FA0F00");
    map.put("Agda", "#315665");
    map.put("Aiken", "#640FF8");
    map.put("Alloy", "#64C800");
    map.put("Alpine Abuild", "#0D597F");
    map.put("Altium Designer", "#A89663");
    map.put("AngelScript", "#C7D7DC");
    map.put("Answer Set Programming", "#A9CC29");
    map.put("Ant Build System", "#A9157E");
    map.put("Antlers", "#FF269E");
    map.put("ApacheConf", "#D12127");
    map.put("Apex", "#1797C0");
    map.put("Apollo Guidance Computer", "#0B3D91");
    map.put("AppleScript", "#101F1F");
    map.put("Arc", "#AA2AFE");
    map.put("AsciiDoc", "#73A0C5");
    map.put("AspectJ", "#A957B0");
    map.put("Assembly", "#6E4C13");
    map.put("Astro", "#FF5A03");
    map.put("Asymptote", "#FF0000");
    map.put("Augeas", "#9CC134");
    map.put("AutoHotkey", "#6594B9");
    map.put("AutoIt", "#1C3552");
    map.put("Avro IDL", "#0040FF");
    map.put("Awk", "#C30E9B");
    map.put("B (Formal Method)", "#8AA8C5");
    map.put("B4X", "#00E4FF");
    map.put("BASIC", "#FF0000");
    map.put("BQN", "#2B7067");
    map.put("Ballerina", "#FF5000");
    map.put("Batchfile", "#C1F12E");
    map.put("Beef", "#A52F4E");
    map.put("Berry", "#15A13C");
    map.put("BibTeX", "#778899");
    map.put("Bicep", "#519ABA");
    map.put("Bikeshed", "#5562AC");
    map.put("Bison", "#6A463F");
    map.put("BitBake", "#00BCE4");
    map.put("Blade", "#F7523F");
    map.put("BlitzBasic", "#00FFAE");
    map.put("BlitzMax", "#CD6400");
    map.put("Bluespec", "#12223C");
    map.put("Bluespec BH", "#12223C");
    map.put("Boo", "#D4BEC1");
    map.put("Boogie", "#C80FA0");
    map.put("Brainfuck", "#2F2530");
    map.put("BrighterScript", "#66AABB");
    map.put("Brightscript", "#662D91");
    map.put("Browserslist", "#FFD539");
    map.put("Bru", "#F4AA41");
    map.put("BuildStream", "#006BFF");
    map.put("C", "#555555");
    map.put("C#", "#178600");
    map.put("C++", "#F34B7D");
    map.put("C3", "#2563EB");
    map.put("CAP CDS", "#0092D1");
    map.put("CLIPS", "#00A300");
    map.put("CMake", "#DA3434");
    map.put("COLLADA", "#F1A42B");
    map.put("CQL", "#006091");
    map.put("CSON", "#244776");
    map.put("CSS", "#663399");
    map.put("CSV", "#237346");
    map.put("CUE", "#5886E1");
    map.put("CWeb", "#00007A");
    map.put("Cabal Config", "#483465");
    map.put("Caddyfile", "#22B638");
    map.put("Cadence", "#00EF8B");
    map.put("Cairo", "#FF4A48");
    map.put("Cairo Zero", "#FF4A48");
    map.put("CameLIGO", "#3BE133");
    map.put("Cangjie", "#00868B");
    map.put("Cap'n Proto", "#C42727");
    map.put("Carbon", "#222222");
    map.put("Ceylon", "#DFA535");
    map.put("Chapel", "#8DC63F");
    map.put("ChucK", "#3F8000");
    map.put("Circom", "#707575");
    map.put("Cirru", "#CCCCFF");
    map.put("Clarion", "#DB901E");
    map.put("Clarity", "#5546FF");
    map.put("Classic ASP", "#6A40FD");
    map.put("Clean", "#3F85AF");
    map.put("Click", "#E4E6F3");
    map.put("Clojure", "#DB5855");
    map.put("Closure Templates", "#0D948F");
    map.put("Cloud Firestore Security Rules", "#FFA000");
    map.put("Clue", "#0009B5");
    map.put("CodeQL", "#140F46");
    map.put("CoffeeScript", "#244776");
    map.put("ColdFusion", "#ED2CD6");
    map.put("ColdFusion CFC", "#ED2CD6");
    map.put("Common Lisp", "#3FB68B");
    map.put("Common Workflow Language", "#B5314C");
    map.put("Component Pascal", "#B0CE4E");
    map.put("Cooklang", "#E15A29");
    map.put("Crystal", "#000100");
    map.put("Csound", "#1A1A1A");
    map.put("Csound Document", "#1A1A1A");
    map.put("Csound Score", "#1A1A1A");
    map.put("Cuda", "#3A4E3A");
    map.put("Curry", "#531242");
    map.put("Cylc", "#00B3FD");
    map.put("Cypher", "#34C0EB");
    map.put("Cython", "#FEDF5B");
    map.put("D", "#BA595E");
    map.put("D2", "#526EE8");
    map.put("DM", "#447265");
    map.put("Dafny", "#FFEC25");
    map.put("Darcs Patch", "#8EFF23");
    map.put("Dart", "#00B4AB");
    map.put("Daslang", "#D3D3D3");
    map.put("DataWeave", "#003A52");
    map.put("Debian Package Control File", "#D70751");
    map.put("DenizenScript", "#FBEE96");
    map.put("Dhall", "#DFAFFF");
    map.put("DirectX 3D File", "#AACE60");
    map.put("Dockerfile", "#384D54");
    map.put("Dogescript", "#CCA760");
    map.put("Dotenv", "#E5D559");
    map.put("Dune", "#89421E");
    map.put("Dylan", "#6C616E");
    map.put("E", "#CCCE35");
    map.put("ECL", "#8A1267");
    map.put("ECLiPSe", "#001D9D");
    map.put("EJS", "#A91E50");
    map.put("EQ", "#A78649");
    map.put("Earthly", "#2AF0FF");
    map.put("Easybuild", "#069406");
    map.put("Ecere Projects", "#913960");
    map.put("Ecmarkup", "#EB8131");
    map.put("Edge", "#0DFFE0");
    map.put("EdgeQL", "#31A7FF");
    map.put("EditorConfig", "#FFF1F2");
    map.put("Eiffel", "#4D6977");
    map.put("Elixir", "#6E4A7E");
    map.put("Elm", "#60B5CC");
    map.put("Elvish", "#55BB55");
    map.put("Elvish Transcript", "#55BB55");
    map.put("Emacs Lisp", "#C065DB");
    map.put("EmberScript", "#FFF4F3");
    map.put("Erlang", "#B83998");
    map.put("Euphoria", "#FF790B");
    map.put("F#", "#B845FC");
    map.put("F*", "#572E30");
    map.put("FIGlet Font", "#FFDDBB");
    map.put("FIRRTL", "#2F632F");
    map.put("FLUX", "#88CCFF");
    map.put("Factor", "#636746");
    map.put("Fancy", "#7B9DB4");
    map.put("Fantom", "#14253C");
    map.put("Faust", "#C37240");
    map.put("Fennel", "#FFF3D7");
    map.put("Filebench WML", "#F6B900");
    map.put("FlatBuffers", "#ED284A");
    map.put("Flix", "#D44A45");
    map.put("Fluent", "#FFCC33");
    map.put("Forth", "#341708");
    map.put("Fortran", "#4D41B1");
    map.put("Fortran Free Form", "#4D41B1");
    map.put("FreeBASIC", "#141AC9");
    map.put("FreeMarker", "#0050B2");
    map.put("Frege", "#00CAFE");
    map.put("Futhark", "#5F021F");
    map.put("G-code", "#D08CF2");
    map.put("GAML", "#FFC766");
    map.put("GAMS", "#F49A22");
    map.put("GAP", "#0000CC");
    map.put("GCC Machine Description", "#FFCFAB");
    map.put("GDScript", "#355570");
    map.put("GDShader", "#478CBF");
    map.put("GEDCOM", "#003058");
    map.put("GLSL", "#5686A5");
    map.put("GSC", "#FF6800");
    map.put("Game Maker Language", "#71B417");
    map.put("Gemfile.lock", "#701516");
    map.put("Gemini", "#FF6900");
    map.put("Genero 4gl", "#63408E");
    map.put("Genero per", "#D8DF39");
    map.put("Genie", "#FB855D");
    map.put("Genshi", "#951531");
    map.put("Gentoo Ebuild", "#9400FF");
    map.put("Gentoo Eclass", "#9400FF");
    map.put("Gerber Image", "#D20B00");
    map.put("Gherkin", "#5B2063");
    map.put("Git Attributes", "#F44D27");
    map.put("Git Commit", "#F44D27");
    map.put("Git Config", "#F44D27");
    map.put("Git Revision List", "#F44D27");
    map.put("Gleam", "#FFAFF3");
    map.put("Glimmer JS", "#F5835F");
    map.put("Glimmer TS", "#3178C6");
    map.put("Glyph", "#C1AC7F");
    map.put("Gnuplot", "#F0A9F0");
    map.put("Go", "#00ADD8");
    map.put("Go Checksums", "#00ADD8");
    map.put("Go Module", "#00ADD8");
    map.put("Go Template", "#00ADD8");
    map.put("Go Workspace", "#00ADD8");
    map.put("Godot Resource", "#355570");
    map.put("Golo", "#88562A");
    map.put("Gosu", "#82937F");
    map.put("Grace", "#615F8B");
    map.put("Gradle", "#02303A");
    map.put("Gradle Kotlin DSL", "#02303A");
    map.put("Grammatical Framework", "#FF0000");
    map.put("GraphQL", "#E10098");
    map.put("Graphviz (DOT)", "#2596BE");
    map.put("Groovy", "#4298B8");
    map.put("Groovy Server Pages", "#4298B8");
    map.put("HAProxy", "#106DA9");
    map.put("HCL", "#844FBA");
    map.put("HIP", "#4F3A4F");
    map.put("HLSL", "#AACE60");
    map.put("HOCON", "#9FF8EE");
    map.put("HTML", "#E34C26");
    map.put("HTML+ECR", "#2E1052");
    map.put("HTML+EEX", "#6E4A7E");
    map.put("HTML+ERB", "#701516");
    map.put("HTML+PHP", "#4F5D95");
    map.put("HTML+Razor", "#512BE4");
    map.put("HTTP", "#005C9C");
    map.put("HXML", "#F68712");
    map.put("Hack", "#878787");
    map.put("Haml", "#ECE2A9");
    map.put("Handlebars", "#F7931E");
    map.put("Harbour", "#0E60E3");
    map.put("Hare", "#9D7424");
    map.put("Haskell", "#5E5086");
    map.put("Haxe", "#DF7900");
    map.put("HiveQL", "#DCE200");
    map.put("HolyC", "#FFEFAF");
    map.put("Hosts File", "#308888");
    map.put("Hurl", "#FF0288");
    map.put("Hy", "#7790B2");
    map.put("IDL", "#A3522F");
    map.put("IGOR Pro", "#0000CC");
    map.put("IL Assembly", "#512BD4");
    map.put("INI", "#D1DBE0");
    map.put("ISPC", "#2D68B1");
    map.put("Idris", "#B30000");
    map.put("Ignore List", "#000000");
    map.put("ImageJ Macro", "#99AAFF");
    map.put("Imba", "#16CEC6");
    map.put("Inno Setup", "#264B99");
    map.put("Io", "#A9188D");
    map.put("Ioke", "#078193");
    map.put("Isabelle", "#FEFE00");
    map.put("Isabelle ROOT", "#FEFE00");
    map.put("J", "#9EEDFF");
    map.put("JAR Manifest", "#B07219");
    map.put("JCL", "#D90E09");
    map.put("JFlex", "#DBCA00");
    map.put("JSON", "#292929");
    map.put("JSON with Comments", "#292929");
    map.put("JSON5", "#267CB9");
    map.put("JSONLD", "#0C479C");
    map.put("JSONiq", "#40D47E");
    map.put("Jac", "#FC792D");
    map.put("Jai", "#AB8B4B");
    map.put("Janet", "#0886A5");
    map.put("Jasmin", "#D03600");
    map.put("Java", "#B07219");
    map.put("Java Properties", "#2A6277");
    map.put("Java Server Pages", "#2A6277");
    map.put("Java Template Engine", "#2A6277");
    map.put("JavaScript", "#F1E05A");
    map.put("JavaScript+ERB", "#F1E05A");
    map.put("Jest Snapshot", "#15C213");
    map.put("JetBrains MPS", "#21D789");
    map.put("Jinja", "#A52A22");
    map.put("Jison", "#56B3CB");
    map.put("Jison Lex", "#56B3CB");
    map.put("Jolie", "#843179");
    map.put("Jsonnet", "#0064BD");
    map.put("Julia", "#A270BA");
    map.put("Julia REPL", "#A270BA");
    map.put("Jupyter Notebook", "#DA5B0B");
    map.put("Just", "#384D54");
    map.put("KCL", "#7ABABF");
    map.put("KDL", "#FFB3B3");
    map.put("KFramework", "#4195C5");
    map.put("KRL", "#28430A");
    map.put("Kaitai Struct", "#773B37");
    map.put("KakouneScript", "#6F8042");
    map.put("KerboScript", "#41ADF0");
    map.put("KiCad Layout", "#2F4AAB");
    map.put("KiCad Legacy Layout", "#2F4AAB");
    map.put("KiCad Schematic", "#2F4AAB");
    map.put("KoLmafia ASH", "#B9D9B9");
    map.put("Koka", "#215166");
    map.put("Kotlin", "#A97BFF");
    map.put("LFE", "#4C3023");
    map.put("LLVM", "#185619");
    map.put("LOLCODE", "#CC9900");
    map.put("LSL", "#3D9970");
    map.put("LabVIEW", "#FEDE06");
    map.put("Lambdapi", "#8027A3");
    map.put("Langium", "#2C8C87");
    map.put("Lark", "#2980B9");
    map.put("Lasso", "#999999");
    map.put("Latte", "#F2A542");
    map.put("Leo", "#C4FFC2");
    map.put("Less", "#1D365D");
    map.put("Lex", "#DBCA00");
    map.put("LigoLANG", "#0E74FF");
    map.put("LilyPond", "#9CCC7C");
    map.put("Liquid", "#67B8DE");
    map.put("Liquidsoap", "#990066");
    map.put("Literate Agda", "#315665");
    map.put("Literate CoffeeScript", "#244776");
    map.put("Literate Haskell", "#5E5086");
    map.put("LiveCode Script", "#0C5BA5");
    map.put("LiveScript", "#499886");
    map.put("Logtalk", "#295B9A");
    map.put("LookML", "#652B81");
    map.put("Lua", "#000080");
    map.put("Luau", "#00A2FF");
    map.put("M3U", "#179C7D");
    map.put("MATLAB", "#E16737");
    map.put("MAXScript", "#00A6A6");
    map.put("MDX", "#FCB32C");
    map.put("MLIR", "#5EC8DB");
    map.put("MQL4", "#62A8D6");
    map.put("MQL5", "#4A76B8");
    map.put("MTML", "#B7E1F4");
    map.put("Macaulay2", "#D8FFFF");
    map.put("Makefile", "#427819");
    map.put("Mako", "#7E858D");
    map.put("Markdown", "#083FA1");
    map.put("Marko", "#42BFF2");
    map.put("Mask", "#F97732");
    map.put("Mathematical Programming System", "#0530AD");
    map.put("Max", "#C4A79C");
    map.put("MeTTa", "#6A5ACD");
    map.put("Mercury", "#FF2B2B");
    map.put("Mermaid", "#FF3670");
    map.put("Meson", "#007800");
    map.put("Metal", "#8F14E9");
    map.put("MiniYAML", "#FF1111");
    map.put("MiniZinc", "#06A9E6");
    map.put("Mint", "#02B046");
    map.put("Mirah", "#C7A938");
    map.put("Modelica", "#DE1D31");
    map.put("Modula-2", "#10253F");
    map.put("Modula-3", "#223388");
    map.put("Mojo", "#FF4C1F");
    map.put("Monkey C", "#8D6747");
    map.put("MoonBit", "#B92381");
    map.put("MoonScript", "#FF4585");
    map.put("Motoko", "#FBB03B");
    map.put("Motorola 68K Assembly", "#005DAA");
    map.put("Move", "#4A137A");
    map.put("Mustache", "#724B3B");
    map.put("NCL", "#28431F");
    map.put("NMODL", "#00356B");
    map.put("NPM Config", "#CB3837");
    map.put("NWScript", "#111522");
    map.put("Nasal", "#1D2C4E");
    map.put("Nearley", "#990000");
    map.put("Nemerle", "#3D3C6E");
    map.put("NetLinx", "#0AA0FF");
    map.put("NetLinx+ERB", "#747FAA");
    map.put("NetLogo", "#FF6375");
    map.put("NewLisp", "#87AED7");
    map.put("Nextflow", "#3AC486");
    map.put("Nginx", "#009639");
    map.put("Nickel", "#E0C3FC");
    map.put("Nim", "#FFC200");
    map.put("Nit", "#009917");
    map.put("Nix", "#7E7EFF");
    map.put("Noir", "#2F1F49");
    map.put("Nu", "#C9DF40");
    map.put("NumPy", "#9C8AF9");
    map.put("Nunjucks", "#3D8137");
    map.put("Nushell", "#4E9906");
    map.put("OASv2-json", "#85EA2D");
    map.put("OASv2-yaml", "#85EA2D");
    map.put("OASv3-json", "#85EA2D");
    map.put("OASv3-yaml", "#85EA2D");
    map.put("OCaml", "#EF7A08");
    map.put("OMNeT++ MSG", "#A0E0A0");
    map.put("OMNeT++ NED", "#08607C");
    map.put("ObjectScript", "#424893");
    map.put("Objective-C", "#438EFF");
    map.put("Objective-C++", "#6866FB");
    map.put("Objective-J", "#FF0C5A");
    map.put("Odin", "#60AFFE");
    map.put("Omgrofl", "#CABBFF");
    map.put("Opal", "#F7EDE0");
    map.put("Open Policy Agent", "#7D9199");
    map.put("OpenAPI Specification v2", "#85EA2D");
    map.put("OpenAPI Specification v3", "#85EA2D");
    map.put("OpenCL", "#ED2E2D");
    map.put("OpenEdge ABL", "#5CE600");
    map.put("OpenQASM", "#AA70FF");
    map.put("OpenSCAD", "#E5CD45");
    map.put("Option List", "#476732");
    map.put("Org", "#77AA99");
    map.put("OverpassQL", "#CCE2AA");
    map.put("Oxygene", "#CDD0E3");
    map.put("Oz", "#FAB738");
    map.put("P4", "#7055B5");
    map.put("PDDL", "#0D00FF");
    map.put("PEG.js", "#234D6B");
    map.put("PHP", "#4F5D95");
    map.put("PLSQL", "#DAD8D8");
    map.put("PLpgSQL", "#336790");
    map.put("POV-Ray SDL", "#6BAC65");
    map.put("Pact", "#F7A8B8");
    map.put("Pan", "#CC0000");
    map.put("Papyrus", "#6600CC");
    map.put("Parrot", "#F3CA0A");
    map.put("Pascal", "#E3F171");
    map.put("Pawn", "#DBB284");
    map.put("Pep8", "#C76F5B");
    map.put("Perl", "#0298C3");
    map.put("PicoLisp", "#6067AF");
    map.put("PigLatin", "#FCD7DE");
    map.put("Pike", "#005390");
    map.put("Pip Requirements", "#FFD343");
    map.put("Pkl", "#6B9543");
    map.put("PlantUML", "#FBBD16");
    map.put("PogoScript", "#D80074");
    map.put("Polar", "#AE81FF");
    map.put("Portugol", "#F8BD00");
    map.put("PostCSS", "#DC3A0C");
    map.put("PostScript", "#DA291C");
    map.put("PowerBuilder", "#8F0F8D");
    map.put("PowerShell", "#012456");
    map.put("Praat", "#C8506D");
    map.put("Prisma", "#0C344B");
    map.put("Processing", "#0096D8");
    map.put("Procfile", "#3B2F63");
    map.put("Prolog", "#74283C");
    map.put("Promela", "#DE0000");
    map.put("Propeller Spin", "#7FA2A7");
    map.put("Pug", "#A86454");
    map.put("Puppet", "#302B6D");
    map.put("PureBasic", "#5A6986");
    map.put("PureScript", "#1D222D");
    map.put("Pyret", "#EE1E10");
    map.put("Python", "#3572A5");
    map.put("Python console", "#3572A5");
    map.put("Python traceback", "#3572A5");
    map.put("Q#", "#FED659");
    map.put("QML", "#44A51C");
    map.put("Qt Script", "#00B841");
    map.put("Quake", "#882233");
    map.put("QuakeC", "#975777");
    map.put("QuickBASIC", "#008080");
    map.put("Quint", "#9D6CE5");
    map.put("R", "#198CE7");
    map.put("RAML", "#77D9FB");
    map.put("RAScript", "#2C97FA");
    map.put("RBS", "#701516");
    map.put("RDoc", "#701516");
    map.put("REXX", "#D90E09");
    map.put("RMarkdown", "#198CE7");
    map.put("RON", "#A62C00");
    map.put("ROS Interface", "#22314E");
    map.put("RPGLE", "#2BDE21");
    map.put("RUNOFF", "#665A4E");
    map.put("Racket", "#3C5CAA");
    map.put("Ragel", "#9D5200");
    map.put("Raku", "#0000FB");
    map.put("Rascal", "#FFFAA0");
    map.put("ReScript", "#ED5051");
    map.put("Reason", "#FF5847");
    map.put("ReasonLIGO", "#FF5847");
    map.put("Rebol", "#358A5B");
    map.put("Record Jar", "#0673BA");
    map.put("Red", "#F50000");
    map.put("Regular Expression", "#009A00");
    map.put("Ren'Py", "#FF7F7F");
    map.put("Rez", "#FFDAB3");
    map.put("Ring", "#2D54CB");
    map.put("Riot", "#A71E49");
    map.put("RobotFramework", "#00C0B5");
    map.put("Roc", "#7C38F5");
    map.put("Rocq Prover", "#D0B68C");
    map.put("Roff", "#ECDEBE");
    map.put("Roff Manpage", "#ECDEBE");
    map.put("Rouge", "#CC0088");
    map.put("RouterOS Script", "#DE3941");
    map.put("Ruby", "#701516");
    map.put("Rust", "#DEA584");
    map.put("SAS", "#B34936");
    map.put("SCSS", "#C6538C");
    map.put("SPARQL", "#0C4597");
    map.put("SQF", "#3F3F3F");
    map.put("SQL", "#E38C00");
    map.put("SQLPL", "#E38C00");
    map.put("SRecode Template", "#348A34");
    map.put("STL", "#373B5E");
    map.put("SVG", "#FF9900");
    map.put("Sail", "#259DD5");
    map.put("SaltStack", "#646464");
    map.put("Sass", "#A53B70");
    map.put("Scala", "#C22D40");
    map.put("Scaml", "#BD181A");
    map.put("Scenic", "#FDC700");
    map.put("Scheme", "#1E4AEC");
    map.put("Scilab", "#CA0F21");
    map.put("Self", "#0579AA");
    map.put("ShaderLab", "#222C37");
    map.put("Shell", "#89E051");
    map.put("ShellCheck Config", "#CECFCB");
    map.put("Shen", "#120F14");
    map.put("Simple File Verification", "#C9BFED");
    map.put("Singularity", "#64E6AD");
    map.put("Slang", "#1FBEC9");
    map.put("Slash", "#007EFF");
    map.put("Slice", "#003FA2");
    map.put("Slim", "#2B2B2B");
    map.put("Slint", "#2379F4");
    map.put("SmPL", "#C94949");
    map.put("Smalltalk", "#596706");
    map.put("Smarty", "#F0C040");
    map.put("Smithy", "#C44536");
    map.put("Snakemake", "#419179");
    map.put("Solidity", "#AA6746");
    map.put("SourcePawn", "#F69E1D");
    map.put("SpiceDB Schema", "#A5318A");
    map.put("Squirrel", "#800000");
    map.put("Stan", "#B2011D");
    map.put("Standard ML", "#DC566D");
    map.put("Starlark", "#76D275");
    map.put("Stata", "#1A5F91");
    map.put("StringTemplate", "#3FB34F");
    map.put("Stylus", "#FF6347");
    map.put("SubRip Text", "#9E0101");
    map.put("SugarSS", "#2FCC9F");
    map.put("SuperCollider", "#46390B");
    map.put("SurrealQL", "#FF00A0");
    map.put("Survex data", "#FFCC99");
    map.put("Svelte", "#FF3E00");
    map.put("Sway", "#00F58C");
    map.put("Sweave", "#198CE7");
    map.put("Swift", "#F05138");
    map.put("SystemVerilog", "#DAE1C2");
    map.put("TI Program", "#A0AA87");
    map.put("TL-Verilog", "#C40023");
    map.put("TLA", "#4B0079");
    map.put("TMDL", "#F0C913");
    map.put("TOML", "#9C4221");
    map.put("TSQL", "#E38C00");
    map.put("TSV", "#237346");
    map.put("TSX", "#3178C6");
    map.put("TXL", "#0178B8");
    map.put("Tact", "#48B5FF");
    map.put("Talon", "#333333");
    map.put("Tcl", "#E4CC98");
    map.put("TeX", "#3D6117");
    map.put("Teal", "#00B1BC");
    map.put("Terra", "#00004C");
    map.put("Terraform Template", "#7B42BB");
    map.put("TextGrid", "#C8506D");
    map.put("TextMate Properties", "#DF66E4");
    map.put("Textile", "#FFE7AC");
    map.put("Thrift", "#D12127");
    map.put("Toit", "#C2C9FB");
    map.put("Tor Config", "#59316B");
    map.put("Tree-sitter Query", "#8EA64C");
    map.put("Turing", "#CF142B");
    map.put("Twig", "#C1D026");
    map.put("TypeScript", "#3178C6");
    map.put("TypeSpec", "#4A3665");
    map.put("Typst", "#239DAD");
    map.put("Unified Parallel C", "#4E3617");
    map.put("Unity3D Asset", "#222C37");
    map.put("Uno", "#9933CC");
    map.put("UnrealScript", "#A54C4D");
    map.put("Untyped Plutus Core", "#36ADBD");
    map.put("UrWeb", "#CCCCEE");
    map.put("V", "#4F87C4");
    map.put("VBA", "#867DB1");
    map.put("VBScript", "#15DCDC");
    map.put("VCL", "#148AA8");
    map.put("VHDL", "#ADB2CB");
    map.put("Vala", "#A56DE2");
    map.put("Valve Data Format", "#F26025");
    map.put("Velocity Template Language", "#507CFF");
    map.put("Vento", "#FF0080");
    map.put("Verilog", "#B2B7F8");
    map.put("Vim Help File", "#199F4B");
    map.put("Vim Script", "#199F4B");
    map.put("Vim Snippet", "#199F4B");
    map.put("Visual Basic .NET", "#945DB7");
    map.put("Visual Basic 6.0", "#2C6353");
    map.put("Volt", "#1F1F1F");
    map.put("Vue", "#41B883");
    map.put("Vyper", "#9F4CF2");
    map.put("WDL", "#42F1F4");
    map.put("WGSL", "#1A5E9A");
    map.put("Web Ontology Language", "#5B70BD");
    map.put("WebAssembly", "#04133B");
    map.put("WebAssembly Interface Type", "#6250E7");
    map.put("Whiley", "#D5C397");
    map.put("Wikitext", "#FC5757");
    map.put("Windows Registry Entries", "#52D5FF");
    map.put("Witcher Script", "#FF0000");
    map.put("Wolfram Language", "#DD1100");
    map.put("Wollok", "#A23738");
    map.put("World of Warcraft Addon Data", "#F7E43F");
    map.put("Wren", "#383838");
    map.put("X10", "#4B6BEF");
    map.put("XC", "#99DA07");
    map.put("XML", "#0060AC");
    map.put("XML Property List", "#0060AC");
    map.put("XQuery", "#5232E7");
    map.put("XSLT", "#EB8CEB");
    map.put("Xmake", "#22A079");
    map.put("Xojo", "#81BD41");
    map.put("Xonsh", "#285EEF");
    map.put("Xtend", "#24255D");
    map.put("YAML", "#CB171E");
    map.put("YARA", "#220000");
    map.put("YASnippet", "#32AB90");
    map.put("Yacc", "#4B6C4B");
    map.put("Yul", "#794932");
    map.put("ZAP", "#0D665E");
    map.put("ZIL", "#DC75E5");
    map.put("ZenScript", "#00BCD1");
    map.put("Zephir", "#118F9E");
    map.put("Zig", "#EC915C");
    map.put("Zimpl", "#D67711");
    map.put("Zmodel", "#FF7100");
    map.put("crontab", "#EAD7AC");
    map.put("eC", "#913960");
    map.put("fish", "#4AAE47");
    map.put("hoon", "#00B171");
    map.put("iCalendar", "#EC564C");
    map.put("jq", "#C7254E");
    map.put("kvlang", "#1DA6E0");
    map.put("mIRC Script", "#3D57C3");
    map.put("mcfunction", "#E22837");
    map.put("mdsvex", "#5F9EA0");
    map.put("mupad", "#244963");
    map.put("nanorc", "#2D004D");
    map.put("nesC", "#94B0C7");
    map.put("ooc", "#B0B77E");
    map.put("q", "#0040CD");
    map.put("reStructuredText", "#141414");
    map.put("sed", "#64B970");
    map.put("templ", "#66D0DD");
    map.put("vCard", "#EE2647");
    map.put("wisp", "#7582D1");
    map.put("xBase", "#403A40");

    GITHUB_LANGUAGE_COLORS = Collections.unmodifiableMap(map);
    Map<String, String> extMap = new HashMap<>();

    extMap.put("html", map.get("HTML"));
    extMap.put("htm", map.get("HTML"));
    extMap.put("xhtml", map.get("HTML"));
    extMap.put("js", map.get("JavaScript"));
    extMap.put("mjs", map.get("JavaScript"));
    extMap.put("cjs", map.get("JavaScript"));
    extMap.put("ts", map.get("TypeScript"));
    extMap.put("tsx", map.get("TSX"));
    extMap.put("css", map.get("CSS"));
    extMap.put("scss", map.get("SCSS"));
    extMap.put("sass", map.get("Sass"));
    extMap.put("less", map.get("Less"));
    extMap.put("vue", map.get("Vue"));
    extMap.put("svelte", map.get("Svelte"));
    extMap.put("jsx", map.get("JavaScript"));
    extMap.put("py", map.get("Python"));
    extMap.put("pyw", map.get("Python"));
    extMap.put("pyx", map.get("Python"));
    extMap.put("java", map.get("Java"));
    extMap.put("class", map.get("Java"));
    extMap.put("c", map.get("C"));
    extMap.put("h", map.get("C"));
    extMap.put("cpp", map.get("C++"));
    extMap.put("cc", map.get("C++"));
    extMap.put("cxx", map.get("C++"));
    extMap.put("hpp", map.get("C++"));
    extMap.put("hh", map.get("C++"));
    extMap.put("hxx", map.get("C++"));
    extMap.put("cs", map.get("C#"));
    extMap.put("csx", map.get("C#"));
    extMap.put("rb", map.get("Ruby"));
    extMap.put("rbw", map.get("Ruby"));
    extMap.put("php", map.get("PHP"));
    extMap.put("phtml", map.get("PHP"));
    extMap.put("php3", map.get("PHP"));
    extMap.put("php4", map.get("PHP"));
    extMap.put("php5", map.get("PHP"));
    extMap.put("swift", map.get("Swift"));
    extMap.put("go", map.get("Go"));
    extMap.put("rs", map.get("Rust"));
    extMap.put("kt", map.get("Kotlin"));
    extMap.put("kts", map.get("Kotlin"));
    extMap.put("scala", map.get("Scala"));
    extMap.put("sc", map.get("Scala"));
    extMap.put("pl", map.get("Perl"));
    extMap.put("pm", map.get("Perl"));
    extMap.put("sh", map.get("Shell"));
    extMap.put("bash", map.get("Shell"));
    extMap.put("zsh", map.get("Shell"));
    extMap.put("fish", map.get("fish"));
    extMap.put("sql", map.get("SQL"));
    extMap.put("r", map.get("R"));
    extMap.put("rmd", map.get("RMarkdown"));
    extMap.put("dart", map.get("Dart"));
    extMap.put("lua", map.get("Lua"));
    extMap.put("ex", map.get("Elixir"));
    extMap.put("exs", map.get("Elixir"));
    extMap.put("erl", map.get("Erlang"));
    extMap.put("hrl", map.get("Erlang"));
    extMap.put("fs", map.get("F#"));
    extMap.put("fsi", map.get("F#"));
    extMap.put("fsx", map.get("F#"));
    extMap.put("clj", map.get("Clojure"));
    extMap.put("cljs", map.get("Clojure"));
    extMap.put("cljc", map.get("Clojure"));
    extMap.put("edn", map.get("Clojure"));
    extMap.put("hs", map.get("Haskell"));
    extMap.put("lhs", map.get("Haskell"));
    extMap.put("lisp", map.get("Common Lisp"));
    extMap.put("lsp", map.get("Common Lisp"));
    extMap.put("el", map.get("Emacs Lisp"));
    extMap.put("rkt", map.get("Racket"));
    extMap.put("nim", map.get("Nim"));
    extMap.put("cr", map.get("Crystal"));
    extMap.put("zig", map.get("Zig"));
    extMap.put("asm", map.get("Assembly"));
    extMap.put("s", map.get("Assembly"));
    extMap.put("pas", map.get("Pascal"));
    extMap.put("m", map.get("Objective-C"));
    extMap.put("mm", map.get("Objective-C++"));
    extMap.put("vhd", map.get("VHDL"));
    extMap.put("vhdl", map.get("VHDL"));
    extMap.put("v", map.get("Verilog"));
    extMap.put("sv", map.get("SystemVerilog"));
    extMap.put("tcl", map.get("Tcl"));
    extMap.put("xml", map.get("XML"));
    extMap.put("xsd", map.get("XML"));
    extMap.put("xslt", map.get("XSLT"));
    extMap.put("svg", map.get("SVG"));
    extMap.put("json", map.get("JSON"));
    extMap.put("jsonc", map.get("JSON with Comments"));
    extMap.put("json5", map.get("JSON5"));
    extMap.put("yml", map.get("YAML"));
    extMap.put("yaml", map.get("YAML"));
    extMap.put("toml", map.get("TOML"));
    extMap.put("ini", map.get("INI"));
    extMap.put("cfg", map.get("INI"));
    extMap.put("conf", map.get("ApacheConf"));
    extMap.put("md", map.get("Markdown"));
    extMap.put("markdown", map.get("Markdown"));
    extMap.put("mdown", map.get("Markdown"));
    extMap.put("tex", map.get("TeX"));
    extMap.put("sty", map.get("TeX"));
    extMap.put("dockerfile", map.get("Dockerfile"));
    extMap.put("makefile", map.get("Makefile"));
    extMap.put("mk", map.get("Makefile"));
    extMap.put("gradle", map.get("Gradle"));
    extMap.put("groovy", map.get("Groovy"));
    extMap.put("gsp", map.get("Groovy Server Pages"));
    extMap.put("ps1", map.get("PowerShell"));
    extMap.put("psm1", map.get("PowerShell"));
    extMap.put("psd1", map.get("PowerShell"));

    EXTENSION_COLORS = Collections.unmodifiableMap(extMap);
  }

  public static String getColorForExtension(String extension) {
    if (extension == null) return null;
    String ext = extension.toLowerCase().trim();
    if (ext.startsWith(".")) {
      ext = ext.substring(1);
    }
    return EXTENSION_COLORS.get(ext);
  }
}
