/**
 * Comment by ghost ide
 *
 * @author: Ninjacoder
 */
package ir.hanzodev1375.ghostide.codeeditors.langs.haskell;

import ir.hanzodev1375.ghostide.codeeditors.langs.simple.SimpleLangConfig;
import ir.hanzodev1375.ghostide.codeeditors.langs.simple.SimpleLanguage;

public class HaskellLanguage extends SimpleLanguage {

  private static final String[] WORDS = {
    "case",
    "class",
    "data",
    "default",
    "deriving",
    "do",
    "else",
    "foreign",
    "if",
    "import",
    "in",
    "infix",
    "infixl",
    "infixr",
    "instance",
    "let",
    "module",
    "newtype",
    "of",
    "then",
    "type",
    "where",
    "forall",
    "mdo",
    "rec",
    "family",
    "stock",
    "anyclass",
    "via",
    "role",
    "pattern",
    "static",
    "unsafe",
    "ccall",
    "javascript",
    "export",
    "label",
    "hiding",
    "qualified",
    "as",
    "Int",
    "Integer",
    "Float",
    "Double",
    "Bool",
    "Char",
    "String",
    "Ordering",
    "Maybe",
    "Just",
    "Nothing",
    "Either",
    "Left",
    "Right",
    "IO",
    "Word",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "Word8",
    "Word16",
    "Word32",
    "Word64",
    "Rational",
    "Complex",
    "ST",
    "IORef",
    "STRef",
    "Monad",
    "Functor",
    "Applicative",
    "MonadPlus",
    "Alternative",
    "Traversable",
    "Foldable",
    "Eq",
    "Ord",
    "Enum",
    "Bounded",
    "Num",
    "Integral",
    "Fractional",
    "Floating",
    "RealFrac",
    "Show",
    "Read",
    "Semigroup",
    "Monoid",
    "LT",
    "GT",
    "EQ",
    "True",
    "False",
    "id",
    "const",
    "flip",
    "curry",
    "uncurry",
    "fst",
    "snd",
    "head",
    "last",
    "tail",
    "init",
    "null",
    "length",
    "reverse",
    "map",
    "filter",
    "foldl",
    "foldl1",
    "foldr",
    "foldr1",
    "and",
    "or",
    "any",
    "all",
    "concat",
    "concatMap",
    "sum",
    "product",
    "maximum",
    "minimum",
    "scanl",
    "scanr",
    "iterate",
    "repeat",
    "replicate",
    "cycle",
    "take",
    "drop",
    "takeWhile",
    "dropWhile",
    "span",
    "break",
    "splitAt",
    "notElem",
    "lookup",
    "zip",
    "zip3",
    "zipWith",
    "unzip",
    "lines",
    "words",
    "unwords",
    "unlines",
    "putStrLn",
    "putStr",
    "print",
    "getLine",
    "readFile",
    "writeFile",
    "appendFile",
    "error",
    "undefined",
    "show",
    "read",
    "maybe",
    "either",
    "fmap",
    "return",
    "pure",
    "traverse",
    "sequence",
    "mapM",
    "mapM_",
    "forM",
    "forever",
    "until",
    "odd",
    "even",
    "gcd",
    "lcm",
    "abs",
    "signum",
    "fromIntegral",
    "realToFrac",
    "truncate",
    "ceiling",
    "floor",
    "round",
    "subtract"
  };

  private static final SnippetDef[] SNIPPETS = {
    new SnippetDef("main", "Snippet - Main", "main :: IO ()\nmain = do\n    $0"),
    new SnippetDef("fn", "Snippet - Function", "${1:name} :: ${2:type}\n${1:name} ${3:args} = $0"),
    new SnippetDef(
        "data",
        "Snippet - Data Type",
        "data ${1:Type} = ${2:Constructor}\n    deriving (${3:Show, Eq})"),
  };

  public HaskellLanguage() {
    super(haskellConfig(), WORDS, SNIPPETS);
  }

  private static SimpleLangConfig haskellConfig() {
    var cfg = new SimpleLangConfig();
    cfg.lineComments = new String[] {"--"};
    cfg.blockComment = true;
    return cfg;
  }
}
