/**
 * Comment by ghost ide
 *
 * @author: Ninjacoder
 */
package ir.hanzodev1375.ghostide.codeeditors.langs.julia;

import ir.hanzodev1375.ghostide.codeeditors.langs.simple.SimpleLangConfig;
import ir.hanzodev1375.ghostide.codeeditors.langs.simple.SimpleLanguage;

public class JuliaLanguage extends SimpleLanguage {

  private static final String[] WORDS = {
    "function",
    "end",
    "macro",
    "begin",
    "let",
    "if",
    "elseif",
    "else",
    "while",
    "for",
    "break",
    "continue",
    "return",
    "do",
    "in",
    "isa",
    "where",
    "mutable",
    "struct",
    "abstract",
    "primitive",
    "type",
    "import",
    "export",
    "using",
    "module",
    "baremodule",
    "const",
    "global",
    "local",
    "try",
    "catch",
    "finally",
    "quote",
    "true",
    "false",
    "nothing",
    "missing",
    "and",
    "or",
    "not",
    "Int",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "Int128",
    "UInt",
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "UInt128",
    "Float16",
    "Float32",
    "Float64",
    "Bool",
    "Char",
    "String",
    "Symbol",
    "Any",
    "Nothing",
    "Union",
    "UnionAll",
    "Missing",
    "AbstractArray",
    "Array",
    "Vector",
    "Matrix",
    "Dict",
    "Set",
    "Tuple",
    "NamedTuple",
    "Pair",
    "Range",
    "UnitRange",
    "StepRange",
    "Function",
    "Number",
    "Real",
    "Integer",
    "Signed",
    "Unsigned",
    "Complex",
    "Rational",
    "Irrational",
    "BigInt",
    "BigFloat",
    "IO",
    "Task",
    "print",
    "println",
    "show",
    "dump",
    "push!",
    "pop!",
    "append!",
    "length",
    "size",
    "ndims",
    "zeros",
    "ones",
    "fill",
    "range",
    "collect",
    "map",
    "mapreduce",
    "filter",
    "reduce",
    "foldl",
    "foldr",
    "sum",
    "prod",
    "minimum",
    "maximum",
    "sort",
    "sort!",
    "unique",
    "reverse",
    "keys",
    "values",
    "haskey",
    "get",
    "getindex",
    "setindex!",
    "typeof",
    "sizeof",
    "eltype",
    "convert",
    "parse",
    "rand",
    "randn",
    "error",
    "throw",
    "include",
    "open",
    "read",
    "write",
    "readline",
    "sleep",
    "time",
    "now",
    "abs",
    "round",
    "trunc",
    "floor",
    "ceil",
    "div",
    "rem",
    "mod",
    "sqrt",
    "exp",
    "log"
  };

  private static final SnippetDef[] SNIPPETS = {
    new SnippetDef("func", "Snippet - Function", "function ${1:name}(${2:args})\n    $0\nend"),
    new SnippetDef("struct", "Snippet - Struct", "struct ${1:Name}\n    ${2:field}\nend"),
    new SnippetDef(
        "mstruct", "Snippet - Mutable Struct", "mutable struct ${1:Name}\n    ${2:field}\nend"),
    new SnippetDef("for", "Snippet - For", "for ${1:i} in ${2:range}\n    $0\nend"),
    new SnippetDef("ife", "Snippet - If/Else", "if ${1:condition}\n    $0\nelse\n    \nend"),
  };

  public JuliaLanguage() {
    super(juliaConfig(), WORDS, SNIPPETS);
  }

  private static SimpleLangConfig juliaConfig() {
    var cfg = new SimpleLangConfig();
    cfg.lineComments = new String[] {"#"};
    cfg.tripleStrings = true;
    cfg.annotations = true;
    return cfg;
  }
}
